### ISSUE TITLE
oauth not working

### ISSUE THREAD

**Issue by FireGM** [iris-contrib/adaptors#1]
iris: 6.0
os: ubuntu 16.04

```go
var configs = oauth.Config{
	RequestPath:          "/auth/{provider}",
	RequestPathParam:     "provider",
	CallbackRelativePath: "/callback",
	RouteName:            "auth",

	GithubKey:    "mykey",
	GithubSecret: "secret",
	GithubName:   "github", 
}
```

after `localhost:3000/auth/github` redirect to

`https://github.com/login/oauth/authorize?client_id=myclientid&redirect_uri=http%3A%2F%2F0.0.0.0%3A3000%2Fauth%2F%7Bprovider%7D%2Fgithub%2F%2Fcallback&response_type=code&state=state`

"{provider}" added to "redirect_uri"

https://github.com/iris-contrib/adaptors/blob/master/oauth/config.go#L148 ?

**Comment by matthmsl** [comment]
Same problem here with facebook. Got redirected to http://domain:8080/auth/{provider}/facebook/callback?code=xxxxxxx after facebook login page. Isn't the authentication.Success(handler) supposed to handle this route ? @kataras any clue on what we're doing wrong ?

_iris v6_

`authConfig:=oauth.Config{
		RequestPath:"/auth/{provider}",
		RequestPathParam: "provider",
		CallbackRelativePath:"/callback",
		RouteName:"auth",

		FacebookName:"facebook",
		FacebookKey:config.OAuth.Facebook.Key,
		FacebookSecret:config.OAuth.Facebook.Secret,
	}
	authentication := oauth.New(authConfig)
	authentication.Success(func(c *iris.Context){
		oauthSuccess(c,authentication)
	})
	Endpoint.Adapt(authentication)
	Endpoint.Adapt(iris.TemplateFuncsPolicy{
		"providerURL": func(providerName string) string {
			return Endpoint.URL(authConfig.RouteName, authConfig.RequestPathParam, providerName)
		},
	})
	authentication.Fail(oAuthErrorHandler)`

**Comment by kataras** [comment]
Try with real-domain please, some websites don't allow localhost.

**Comment by matthmsl** [comment]
I did it with real domain ;) 
Just didn't pasted it on comment. BTW I tried to run the example code. It doesn't seem to work as provided. I added a session and a view adapter but I'm still getting 404.

**Comment by FireGM** [comment]
i gave line with error. You concatenate `c.RequestPath + "/" + providerName + "/" + c.CallbackRelativePath` - /auth/:provider + github + /callback = `/auth/:providergithub/callback. Then it do https://github.com/markbates/goth/blob/master/providers/github/github.go#L43
where oauth get it as redirect_uri. Need remove :proveider|{provider} from c.RequestPath before concatenate

**Comment by matthmsl** [comment]
@FireGM have you tried your solution ?

**Comment by kataras** [comment]
@FireGM I think it's not needed if @matthmsl  setted these oauth adaptor's configuration fields correctly: 

```go
	// RequestPath for example "/auth/:provider"
	RequestPath      string
	RequestPathParam string // if RequestPath is: "/auth/:provider" then this field should be "provider""
	// CallbackRelativePath relative to RequestPath, for example "/callback"
	// it will convert to: "/auth/facebook/callback" if facebook provider.
CallbackRelativePath string


```

**Comment by matthmsl** [comment]
@FireGM is right. It seems that there is a mismatch between the request sent to 3rd-part API and what gorillamux is expecting.
For example if you provide a name when you configure oauth, the name is sent to the 3rd-part API and included in the callback URL but routes aren't set properly and keep the default name.

The expected behavior of the code below is 

1. Create routes /auth/google and /auth/google/callback
2. On /auth/google --> send client_id and redirect_uri to 3rd-part API where redirect_uri is domain.com/auth/google/callback
3. On /auth/google/callback --> complete authentication process

```golang
authConfig := oauth.Config{
		RequestPath:          "/auth/{provider}",
		RequestPathParam:     "provider",
		CallbackRelativePath: "/callback",
		RouteName:            "auth",

		GplusName:   "google",
		GplusKey:    config.OAuth.Google.Key,
		GplusSecret: config.OAuth.Google.Secret,
	}
```

Real behaviour is the following :

1. Create routes /auth/google and /auth/{provider}/google//callback
2. On /auth/google --> send client_id and redirect_uri to 3rd-part API where redirect_uri is domain.com/auth/{provider}/google//callback
3. 404 Not found on self-hosted server

I'll fork and try to figure out what's going on this adaptor.

**Comment by kataras** [comment]
Thanks @matthmsl, do whatever needed changes you think that it needs, I'll wait for a PR!!!

**Comment by kataras** [comment]
Update: @matthmsl fixed that with: https://github.com/iris-contrib/adaptors/pull/2 . Thanks him :)
